### ISSUE TITLE
Error in installition

### ISSUE THREAD

**Issue by amirghazi87** [yahyalmh/ChangeWallpaper#2]
Hi
I clone the repository and move all of the files in the repo to ~/.changeWall
when I run the Linux installation file, have some errors
```
Info: you have install python3
Info: create app directory in path:'/home/amir/.changeWall'
Info: coping files...
Info: run app...
grep: /proc//environ: No such file or directory

(process:8615): dconf-WARNING **: 14:25:42.644: failed to commit changes to dconf: The given address is empty
Info: create crontab job to change wallpaper hourly(see crontab file)
Info: download Bing and Nasa wallpaper if net connection was ok
Info: Finished
```
---
i use Linux Mint 20 and Cinnamon DE

**Comment by yahyalmh** [comment]
Hi, 
You do not need to move all project's files to `~/.chageWall` folder and it is because of my bad  English in README file, I am sorry.

To install it, remove the `~/.chageWall` folder first,  clone the project in an arbitrary path(NOT `~/.chageWall` path)  and just run `install.sh` bash under the installation folder. I edited the  README file, take a look at it. 

Please test this way and if the problem exists, install it with `sudo` and comment the result here.

**Comment by amirghazi87** [comment]
I do that work but again :
```
Info: you have install python3
Info: create app directory in path:'/root/.changeWall'
Info: coping files...
Info: run app...
grep: /proc//environ: No such file or directory

(process:67094): dconf-WARNING **: 16:06:18.595: failed to commit changes to dconf: The given address is empty
Info: create crontab job to change wallpaper hourly(see crontab file)
Info: download Bing and Nasa wallpaper if net connection was ok
Info: Finished

```

**Comment by yahyalmh** [comment]
I Updated the change wallpaper bash which would be able to change the wallpaper in your distribution, And I tested it on the Linux Mint 20.2 Mate(Cinnamon DE), it was OK.  In fact setting wallpaper is little different in the Linux distributions. Try a clean install (normally without  `sudo` but if it does not work it can be another chance).

**Comment by yahyalmh** [comment]
Hi @amirghazi87,
Do you try to install after the changes which I did? was is successful or not?

**Comment by yahyalmh** [comment]
I added proper code to change the wallpaper on `Cinnamon` DE, and I tested it. So I close this issue.
